server:
  context-path: /ism
  port: 8080
spring:
  datasource:
  type: com.alibaba.druid.pool.DruidDataSource
  ism:
    driver-class-name: com.mysql.jdbc.Driver
    username: ***
    password: ***
    url: jdbc:mysql://localhost:3306/new_ism?useSSL=false&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: 127.0.0.1
  http:
    multipart:
      max-file-size: 2Mb
      max-request-size: 10Mb
mybatis:
  config-location: classpath:mybatis.xml
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.com.ahsoft.new_ism.entities
  map-underscore-to-camel-case: true
#FileUpload Directory
fileupload:
   rootDir: /img
   dir: D:/IdeaWorkspace/upload/
  #rootDir: img
  #dir: /Users/foxx/
logging:
  level:
    cn.com.ahsoft.new_ism.daos: debug # enable mybatis sql print
#    org.springframework.web: info

qr.url: 
wx.msg.url: 
#OSS配置
oss.endpoint: 
oss.accessKeyId: 
oss.accessKeySecret: 
oss.bucketName:
